### ISSUE TITLE
Structuration of grammar

### ISSUE THREAD

**Issue by xavitator** [Heijix/Warehouse#8]
Separate lexer and parser ;)

**Comment by FauconFan** [comment]
Make the grammar great again.

bdd8d2eb3d3583358f23cd810994650f927de320
d3bc69dcd305d3fbe120a597fb2bb77a8876a098
4672d9857dc46c48b05230c9d6413bad55ea1795

(you may want to see the Grammar file directly)

I think it's more clear, now. But I don't know if it's relevant, because the lexer will have multiple states...
I put every tokens that is allowed for each grammar... Maybe we can use a turing machine and different allowed tokens depending of the state... And just a dynamic list (in every programming language) to store the tokens gradually...

What do you think ?

**Comment by FauconFan** [comment]
83a5ef8c41c85d4c47efb6e069981d92ce906284

**Comment by FauconFan** [comment]
Help wanted label is more for external help. Here we just asking each others

**Comment by xavitator** [comment]
I think that store token is a bad idea... I don't see in which exemple that we need it ?

**Comment by FauconFan** [comment]
dynamic list, it's just terms in programming language... like ArrayList in Java, and vector in cpp. We just happend a new token at the end of list to have a ordered set of tokens. (There is nothing special here...). The idea is to have multiple lists, one for each grammar (Iota, Lambda, Omega), ans so on with sub grammars. But i don't know if it's relevant...

**Comment by xavitator** [comment]
I think too. Storing token leads to memory troubles, if we have a big file.
